            - name: Deploy Azure AD B2C custom policy
  # You may pin to the exact commit or the version.
  # uses: azure-ad-b2c/deploy-trustframework-policy@126e63df5f83fcfad6fbeaefc9a99fec38bb53bf
  uses: azure-ad-b2c/deploy-trustframework-policy@v5.3
  with:
    # The folder where the custom policies files are stored
    folder: 
    # Comma delimiter list of policy files
    files: 
    # The full Azure AD B2C tenant name (for example, contoso.onmicrosoft.com) or GUID
    tenant: 
    # The application Client ID for a service principal which will be used to authenticate to the Microsoft Graph
    clientId: 
    # The application Secret for a service principal which will be used to authenticate to the Microsoft Graph
    clientSecret: 
    # Renumber the orchestration steps. Possible values: true, or false
    renumberSteps: # optional, default is false
    # Add App Insights orchestration steps to the the user journeys.
    addAppInsightsStep: # optional, default is false
    # Log level verbose.
    verbose: # optional, default is false
          
